Document: vnc4
Title: Debian vnc4 Manual
Author: <insert document author here>
Abstract: This manual describes what vnc4 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vnc4/vnc4.sgml.gz

Format: postscript
Files: /usr/share/doc/vnc4/vnc4.ps.gz

Format: text
Files: /usr/share/doc/vnc4/vnc4.text.gz

Format: HTML
Index: /usr/share/doc/vnc4/html/index.html
Files: /usr/share/doc/vnc4/html/*.html

  
